- name: Create a directory /home/backup/mysql
  ansible.builtin.file:
    path: /home/backup/mysql
    state: directory
    mode: '755'
    owner: 'backup'

- name: create mysql user backup
  community.mysql.mysql_user:
    name: "backup"
    password: "{{ backup_password }}"
    priv: '*.*:PROCESS,REPLICATION CLIENT,SELECT,LOCK TABLES'
    login_unix_socket: /var/run/mysqld/mysqld.sock

- name: config mysql
  template:
    src: .my.cnf.j2
    dest: /home/backup/.my.cnf
  no_log: true



- name: schedule MySQL dumps with Cron
  ansible.builtin.cron:
    name: "MySQL dump"
    minute: "10"
    hour: "16"
    weekday: "2"
    job: "mysqldump agama > /home/backup/mysql/agama.sql"
    user: backup
  when: inventory_hostname == mysql_backup_host

- name: schedule MySQL dumps with Cron
  ansible.builtin.cron:
    name: "Full Duplication"
    minute: "11"
    hour: "16"
    weekday: "2"
    job: "duplicity --no-encryption full /home/backup/mysql/ rsync://EdvinToome@backup.larsenbiscuits.io/mysql"
    user: backup
  when: inventory_hostname == mysql_backup_host

- name: schedule MySQL dumps with Cron
  ansible.builtin.cron:
    name: "Incremental Duplication"
    minute: "12"
    hour: "16"
    weekday: "2"
    job: "duplicity --no-encryption incremental /home/backup/mysql/ rsync://EdvinToome@backup.larsenbiscuits.io/mysql"
    user: backup
  when: inventory_hostname == mysql_backup_host

