- name: Install nginx
  ansible.builtin.apt:
    name: nginx-full
#    update_cache: yes

- name: Start service nginx, if not started
  ansible.builtin.service:
    name: nginx
    state: started

- name: Enable service nginx, and not touch the state
  ansible.builtin.service:
    name: nginx
    enabled: yes

- name: NGINX config
  template:
    src: default.j2
    dest: /etc/nginx/sites-enabled/default
  notify:
    - Restart nginx

