- name: install gpg
  apt:
    name: gnupg,software-properties-common
    state: latest

- name: install ca-certificates
  apt:
    name: ca-certificates
    state: latest

- name: install apt-transport-https
  apt:
    name: apt-transport-https
    state: present

- name: add gpg hey
  apt_key:
    url: "https://packages.grafana.com/gpg.key"
    validate_certs: no
- name: add repository
  apt_repository:
    repo: "deb https://packages.grafana.com/oss/deb stable main"             

- name: install grafana
  apt:
    name: grafana
    state: latest

- name: Enable grafana
  systemd:
    name: grafana-server
    state: started
    daemon_reload: yes
    enabled: yes

- name: Config grafana
  template:
    src: grafana.ini.j2
    dest: /etc/grafana/grafana.ini
  notify: Restart grafana



- name: Restart grafana
  systemd:
    name: grafana-server
    state: restarted
    daemon_reload: yes
    enabled: yes



#- name: Create dashboards
#  ansible.builtin.copy:
#    src: main.json
#    dest: /var/lib/grafana/dashboards/dash.json
#
#- name: Dashboard copy
#  template:
#    src: dashboard.yaml.j2
#    dest: /etc/grafana/provisioning/dashboards/dashboard.yaml
#
#- name: Datasource copy
#  template:
#    src: datasource.yaml.j2
#    dest: /etc/grafana/provisioning/datasources/datasource.yaml