

- name: Create a directory /opt/grafana/provisioning/dashboards
  ansible.builtin.file:
    path: /opt/grafana/provisioning/dashboards
    state: directory
    mode: '0755'

- name: Create a directory /opt/grafana/provisioning/datasources
  ansible.builtin.file:
    path: /opt/grafana/provisioning/datasources
    state: directory
    mode: '0755'
    
- name: Config grafana
  template:
    src: grafana.ini.j2
    dest: /opt/grafana/grafana.ini
  notify: restart grafana
- name: Provisioning Grafana datasource
  template:
    src: datasource.yaml.j2
    dest: /opt/grafana/provisioning/datasources/default.yaml
    mode: '0755'
  notify: restart grafana

- name: Run Grafana container
  community.docker.docker_container:
    name: grafana
    image: grafana/grafana:latest
    state: started
    restart_policy: always
    published_ports: "{{ grafana_port }}:3000"
    volumes:
      - /opt/grafana:/etc/grafana
    env:
      GF_SECURITY_ADMIN_PASSWORD: "{{ grafana_password }}"
      GF_SECURITY_ADMIN_USER: "admin"
#- name: create prometheus datasource
#  community.grafana.grafana_datasource:
#    url: "http://EdvinToome-2:3001"
#    name: prometheus
#    ds_type: prometheus
#    ds_url: "http://EdvinToome-2:9090/prometheus"
#    access: proxy
#    url_username: "admin"
#    url_password: "{{ mysql_password }}"
#    is_default: true
#  

- name: Create a directory /var/lib/grafana/dashboards
  ansible.builtin.file:
    path: /var/lib/grafana/dashboards
    state: directory
    mode: '0755'
  notify: restart grafana
#- name: Provisioning Grafana dashboard
#  template:
#    src: dashboard.yaml.j2
#    dest: /opt/grafana/provisioning/dashboards/default.yaml
#    mode: '0755'


#- name: Move main.json to /opt/grafana/provisioning/dashboards
#  copy:
#    src: main.json
#    dest: /var/lib/grafana/dashboards/main.json
#    mode: '0755'
#

- name: Import dashboard
  copy:
    src: "{{ item }}"
    dest: /opt/grafana/provisioning/dashboards/{{ item }}
    mode: '0755'
  loop:
    - main.json
    - rsyslog.json
    - mysql.json


- name: Wait for Grafana to start
  wait_for:
    port: 3001
    host: EdvinToome-3
    state: started
    timeout: 120

- name: Provision dashboard
  community.grafana.grafana_dashboard:
    grafana_url: "http://EdvinToome-3:3001"
    url_username: "admin"
    url_password: "{{ grafana_password }}"
    state: present
    commit_message: Updated by ansible
    overwrite: yes
    path: /opt/grafana/provisioning/dashboards/{{ item }}
  loop:
    - main.json
    - rsyslog.json
    - mysql.json