

- name: Create a directory /opt/grafana/provisioning/dashboards
  ansible.builtin.file:
    path: /opt/grafana/provisioning/dashboards
    state: directory
    mode: '0755'

- name: Create a directory /opt/grafana/provisioning/datasources
  ansible.builtin.file:
    path: /opt/grafana/provisioning/datasources
    state: directory
    mode: '0755'
    
- name: Config grafana
  template:
    src: grafana.ini.j2
    dest: /opt/grafana/grafana.ini

- name: Provisioning Grafana datasource
  template:
    src: datasource.yaml.j2
    dest: /opt/grafana/provisioning/datasources/default.yaml
    mode: '0755'

- name: Provisioning Grafana Influx
  template:
    src: datasource-influx.yaml.j2
    dest: /opt/grafana/provisioning/datasources/datasource-influx.yaml
    mode: '0755'

- name: Run Grafana container
  community.docker.docker_container:
    name: grafana
    image: grafana/grafana:latest
    state: started
    user: "0:0"
    published_ports: "{{ grafana_port }}:3000"
    volumes:
      - /opt/grafana:/etc/grafana
    env:
      GF_SECURITY_ADMIN_PASSWORD: "{{ mysql_password }}"
      GF_SECURITY_ADMIN_USER: "admin"

#- name: create prometheus datasource
#  community.grafana.grafana_datasource:
#    url: "http://EdvinToome-2:3001"
#    name: prometheus
#    ds_type: prometheus
#    ds_url: "http://EdvinToome-2:9090/prometheus"
#    access: proxy
#    url_username: "admin"
#    url_password: "{{ mysql_password }}"
#    is_default: true
#  

- name: Create a directory /var/lib/grafana/dashboards
  ansible.builtin.file:
    path: /var/lib/grafana/dashboards
    state: directory
    mode: '0755'

#- name: Provisioning Grafana dashboard
#  template:
#    src: dashboard.yaml.j2
#    dest: /opt/grafana/provisioning/dashboards/default.yaml
#    mode: '0755'


#- name: Move main.json to /opt/grafana/provisioning/dashboards
#  copy:
#    src: main.json
#    dest: /var/lib/grafana/dashboards/main.json
#    mode: '0755'
#

- name: Import main.json
  copy:
    src: main.json
    dest: /tmp/main.json
    mode: '0755'


- name: Import Grafana dashboard foo
  community.grafana.grafana_dashboard:
    grafana_url: "http://EdvinToome-2:3001"
    url_username: "admin"
    url_password: "{{ mysql_password }}"
    state: present
    commit_message: Updated by ansible
    overwrite: yes
    path: /tmp/main.json
    org_id: 1