

- name: Create a directory /opt/grafana/provisioning/dashboards
  ansible.builtin.file:
    path: /opt/grafana/provisioning/dashboards
    state: directory
    mode: '0755'

- name: Create a directory /opt/grafana/provisioning/datasources
  ansible.builtin.file:
    path: /opt/grafana/provisioning/datasources
    state: directory
    mode: '0755'
    
- name: Config grafana
  template:
    src: grafana.ini.j2
    dest: /opt/grafana/grafana.ini

- name: Run Grafana container
  community.docker.docker_container:
    name: grafana
    image: grafana/grafana:latest
    state: started
    user: "0:0"
    published_ports: "{{ grafana_port }}:3000"
    volumes:
      - /opt/grafana:/etc/grafana
    env:
      GF_SECURITY_ADMIN_PASSWORD: "{{ mysql_password }}"
      GF_SECURITY_ADMIN_USER: "admin"
