- name: Install uwsgi
  ansible.builtin.apt:
    name: uwsgi
#    update_cache: yes

- name: Install uwsgi-plugin-python3
  ansible.builtin.apt:
    name: uwsgi-plugin-python3
#    update_cache: yes
  

- name: Start service uwsgi, if not started
  ansible.builtin.service:
    name: uwsgi
    state: started

- name: Enable service uwsgi, and not touch the state
  ansible.builtin.service:
    name: uwsgi
    enabled: yes

- name: Configure DNS
  ansible.builtin.template:
    src: resolv.conf.j2
    dest: /etc/resolv.conf
  notify:
    - Restart uwsgi