{
 "title": "Main",
 "time": { "from": "2022-10-11T13:39:48.623Z", "to": "2022-10-11T15:30:42.926Z" },
 "panels": [
  {
   "title": "MySQL status",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "mysql_up", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Bind9",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "bind_up", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "NGINX",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "nginx_up", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "DNS Queries",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(bind_resolver_queries_total[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MySQL queries",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 17, "y": 0 },
   "targets": [
    {
     "expr": "rate(mysql_global_status_commands_total[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "node_memory_MemFree_bytes/node_memory_MemTotal_bytes*100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "NGINX requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "rate(nginx_http_requests_total[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Load",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "1-rate(node_cpu_seconds_total{mode=\"idle\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}