{
 "title": "MySQL",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "MySQL queries",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(mysql_global_status_commands_total{command=\"select\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MySQL server ID",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mysql_global_variables_server_id",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MySQL",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "mysql_up", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "MySQL replication thread",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "mysql_slave_status_slave_sql_running",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MySQL replication thread",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "mysql_slave_status_slave_io_running",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": " MySQL server read only status",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 29 },
   "targets": [
    {
     "expr": "mysql_global_variables_read_only",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}