- name: Install agama dependency
  ansible.builtin.apt:
    name: 
      - python3-flask-sqlalchemy
      - python3-pymysql 
    update_cache: yes

- name: Add the user 'agama'
  ansible.builtin.user:
    name: agama

- name: Create a directory /opt/agama 
  ansible.builtin.file:
    path: /opt/agama
    state: directory
    mode: '0777'
    owner: root

- name: Download agama
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/hudolejev/agama/master/agama.py
    dest: /opt/agama/agama.py
    mode: '0755'

- name: Download agama docker
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/hudolejev/agama/master/Dockerfile
    dest: /opt/agama/Dockerfile
    mode: '0755'

- name: Build an image and push it to a private repo
  community.docker.docker_image:
    build:
      path: /opt/agama
    name: agama
    source: build

- name: Run agama container
  community.docker.docker_container:
    name: agama-{{ ((agama_containers | count) + item) if inventory_hostname == 'EdvinToome-2' else item  }}
    image: agama
    state: started
    user: "0:0"
    restart_policy: always
    published_ports: "{{ agama_port + item }}:8000"
    env:
      AGAMA_DATABASE_URI: mysql+pymysql://{{ mysql_user }}:{{ mysql_password }}@{{ mysql_host }}/{{ mysql_database }}
  loop: "{{ agama_containers }}"