- name: Add the user 'backup'
  ansible.builtin.user:
    name: backup
    generate_ssh_key: yes
    home: /home/backup/
    ssh_key_file: /home/backup/.ssh/id_rsa

- name: Create a 2048-bit SSH key 
  ansible.builtin.user:
    name: backup
    generate_ssh_key: yes
    ssh_key_bits: 2048
    ssh_key_file: .ssh/id_rsa

- name: Copy known hosts
  ansible.builtin.template:
    src: known_hosts.j2
    dest: /home/backup/.ssh/known_hosts
    owner: backup
    group: backup

- name: Create a directory /home/backup/restore
  ansible.builtin.file:
    path: /home/backup/restore
    state: directory
    mode: '755'
    owner: 'backup'

- name: install duplicity
  apt:
    name: duplicity
    state: present
    