- name: Add the user 'backup'
  ansible.builtin.user:
    name: backup
    generate_ssh_key: yes
    home: /home/backup/
    ssh_key_file: /home/backup/.ssh/id_rsa

- name: Add ssh key
  ansible.builtin.known_hosts:
    name: backup
    key: "backup ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIEu6pFFWyuRrl4WGFPQGElYN9txwTGm2wSntcpVAaN90"

- name: Add key
  ansible.builtin.template:
    src: known_hosts.j2
    dest: /home/backup/.ssh/known_hosts
    owner: backup
    group: backup
    mode: 777

