- name: Create a directory /home/backup/influxdb
  ansible.builtin.file:
    path: /home/backup/influxdb
    state: directory
    mode: '755'
    owner: 'backup'

- name: schedule MySQL dumps with Cron
  ansible.builtin.cron:
    name: "MySQL dump"
    minute: "0"
    hour: "0"
    weekday: "0"
    job: "influxd backup -portable /home/backup/influxdb"
    user: backup

- name: schedule MySQL dumps with Cron
  ansible.builtin.cron:
    name: "MySQL dump"
    minute: "0"
    hour: "1"
    weekday: "0"
    job: "duplicity --no-encryption incremental /home/backup/influxdb rsync://EdvinToome@backup.larsenbiscuits.io/influxdb"
    user: backup