- name: Create a directory /home/backup/influxdb
  ansible.builtin.file:
    path: /home/backup/influxdb
    state: directory
    mode: '755'
    owner: 'backup'

- name: schedule Influxdb dumps with Cron
  ansible.builtin.cron:
    name: "InfluxDB dump"
    minute: "10"
    hour: "16"
    weekday: "2"
    job: "influxd backup -portable /home/backup/influxdb"
    user: backup

- name: schedule Influxdb dumps with Cron
  ansible.builtin.cron:
    name: "Influxdb dump"
    minute: "11"
    hour: "16"
    weekday: "2"
    job: "duplicity --no-encryption full /home/backup/influxdb rsync://EdvinToome@backup.larsenbiscuits.io/influxdb"
    user: backup

- name: schedule Influxdb dumps with Cron
  ansible.builtin.cron:
    name: "Influxdb dump"
    minute: "12"
    hour: "16"
    weekday: "2"
    job: "duplicity --no-encryption incremental /home/backup/influxdb rsync://EdvinToome@backup.larsenbiscuits.io/influxdb"
    user: backup