- name: update and install mysql node exporter
  apt:
    name: prometheus-mysqld-exporter  

- name: create mysql user
  community.mysql.mysql_user:
    name: "exporter"
    password: "{{ mysql_password }}"
    priv: '*.*:PROCESS,REPLICATION CLIENT,SELECT'
    login_unix_socket: /var/run/mysqld/mysqld.sock

- name: Enable mysql exporter
  systemd:
    name: prometheus-mysqld-exporter 
    state: started
    daemon_reload: yes
    enabled: yes

- name: config mysql
  template:
    src: .my.cnf.j2
    dest: /var/lib/prometheus/.my.cnf
  no_log: yes 
  notify: restart mysql exporter

- name: config prometheus-mysqld-exporter
  template:
    src: prometheus-mysqld-exporter.j2
    dest: /etc/default/prometheus-mysqld-exporter
  notify: restart mysql exporter