- name: update and install bind exporter
  apt:
    name: prometheus-bind-exporter 

- name: install service
  template:
    src: bind_exporter.service.j2
    dest: /etc/systemd/system/bind_exporter.service
    owner: root
    group: root
    mode: 0755
  notify: restart_bind_exporter

- name: Enable bind exporter
  systemd:
    name: prometheus-bind-exporter 
    state: started
    daemon_reload: yes
    enabled: yes