- name: Restart pinger
  systemd:
    name: pinger
    state: restarted
    daemon_reload: yes
    enabled: yes

- name: Restart telegraf
  systemd:
    name: telegraf
    state: restarted
    daemon_reload: yes
    enabled: yes

- name: Restart influxdb
  systemd:
    name: influxdb
    state: restarted
    daemon_reload: yes
    enabled: yes

- name: Restart rsyslog
  systemd:
    name: rsyslog
    state: restarted
    daemon_reload: yes
    enabled: yes