#Install keepalived
- name: Install keepalived
  ansible.builtin.apt:
    name: keepalived 



- name: Keepalived config
  ansible.builtin.template:
    src: keepalived.conf.j2
    dest: /etc/keepalived/keepalived.conf
  notify:
    - Restart keepalived

- name: Start service keepalived, if not started
  ansible.builtin.service:
    name: keepalived
    state: started


#keepalived user
- name: Add keepalived_script user
  ansible.builtin.user:
    name: keepalived_script
    home: /home/keepalived_script



- name: Add keepalive script
  ansible.builtin.template:
    src: script.sh.j2
    dest: /home/keepalived_script/script.sh
    owner: keepalived_script
    group: keepalived_script
    mode: 0777

- name: Enable service keepalived, and not touch the state
  ansible.builtin.service:
    name: keepalived
    enabled: yes



- name: Create a directory /usr/local/bin/keepalived-exporter/
  ansible.builtin.file:
    path: /usr/local/bin/keepalived-exporter/
    state: directory
    mode: '777'

- name: download and unzip node exporter if not exist
  unarchive:
    src: https://github.com/cafebazaar/keepalived-exporter/releases/download/v1.2.0/keepalived-exporter-1.2.0.linux-amd64.tar.gz
    dest: /usr/local/bin/keepalived-exporter/
    remote_src: yes
    validate_certs: no

- name: config keepalived exporter.service
  template:
    src: keepalived-exporter.service.j2
    dest: /etc/systemd/system/keepalived-exporter.service
    mode: '777'
  notify: Restart keepalived-exporter


- name: Start keepalived exporter
  ansible.builtin.systemd:
    name: keepalived-exporter
    state: started
    enabled: yes