- name: update and install prometheus
  apt:
    name: prometheus
    state: latest

- name: prometheus args
  template:
    src: prometheus.j2
    dest: /etc/default/prometheus
    mode: 0644
    owner: root
    group: root
  notify: restart_prometheus

- name: prometheus configuration file
  template:
    src: prometheus.yml.j2
    dest: "{{ prometheus_dir_configuration }}/prometheus.yml"
    mode: 0755
    owner: prometheus
    group: prometheus
  notify: restart_prometheus


- name: start prometheus
  systemd:
    name: prometheus
    state: started
    enabled: yes  

- name: Install nginx
  ansible.builtin.apt:
    name: nginx-full

- name: Start service nginx, if not started
  ansible.builtin.service:
    name: nginx
    state: started

- name: Enable service nginx, and not touch the state
  ansible.builtin.service:
    name: nginx
    enabled: yes