- name: update and install nginx exporter
  apt:
    name: prometheus-nginx-exporter 

- name: Copy nginx exporter config
  ansible.builtin.template:
    src: prometheus-nginx-exporter.j2
    dest: /etc/default/prometheus-nginx-exporter
  notify: Restart nginx exporter


- name: Enable nginx exporter
  systemd:
    name: prometheus-nginx-exporter 
    state: started
    daemon_reload: yes
    enabled: yes