
- name: Install bind9
  ansible.builtin.apt:
    name: bind9


- name: Configure access rules for DNS server
  ansible.builtin.template:
    src: named.conf.options.j2
    dest: /etc/bind/named.conf.options
  notify:
    - Restart bind9
  
- name: Configure 
  ansible.builtin.template:
    src: named.conf.local.j2
    dest: /etc/bind/named.conf.local
  notify:
    - Restart bind9

- name: Configure DB
  ansible.builtin.template:
    src: db.larsenbiscuits.io.j2
    dest: /var/lib/bind/db.larsenbiscuits.io
  notify:
    - Restart bind9
  when: inventory_hostname in groups['dns_masters']

- name: Configure DB rev
  ansible.builtin.template:
    src: db.rev.j2
    dest: /var/lib/bind/db.rev
  notify:
    - Restart bind9
  when: inventory_hostname in groups['dns_masters']

- name: Configure DNS
  ansible.builtin.template:
    src: resolv.conf.j2
    dest: /etc/resolv.conf
  notify:
    - Restart bind9