- name: Update APT cache
  ansible.builtin.apt:
    cache_valid_time: 86400

- name: config rsyslog
  template:
    src: 50-telegraf.conf.j2
    dest: /etc/rsyslog.d/50-telegraf.conf
    mode: '777'

- name: Restart rsyslog
  systemd:
    name: rsyslog
    state: restarted
    daemon_reload: yes
    enabled: yes